name: flutterapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  firebase_database: ^3.1.3
  provider: ^4.0.4
  fluttertoast: ^4.0.1
  scoped_model: ^1.0.1
  google_nav_bar: ^1.0.1
  line_icons: ^0.2.0
  simple_animations: ^1.3.3
  page_transition: ^1.1.4
  #maps
  http: ^0.12.0+4
  google_maps_webservice: ^0.0.16
  geolocator: any
  google_maps_flutter: ^0.5.25+3
  rxdart: any
  geoflutterfire: ^2.1.0
  location: ^3.0.2
  #font_awesome_flutter: ^8.8.1
  gradient_text: ^1.0.2
  stripe_payment: ^1.0.7
  progress_dialog: ^1.2.2
  font_awesome_flutter: ^8.8.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_bloc: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_credit_card: ^0.1.3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/data.json
    - assets/Apalkoff.jpg
    - assets/creatingprofile.png
    - assets/biscuits.png
    - assets/breads.png
    - assets/cakes.png
    - assets/chocolates.png
    - assets/creatingprofile.png
    - assets/marshmallows.png
    - assets/background.jpg
    - assets/hotel0.jpg
    - assets/buckweat1.jpg
    - assets/orderFoodOnline.jpg
    - assets/onlineMenu.jpg
    - assets/restaurantsNearMe.jpg
    - assets/globus.png
    - assets/globusLogo.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true